// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB8JPwsag4uAuAG09Y2VqEsiXF5q8Qdao',
    appId: '1:948860137355:web:5ad619223a2f4bbbd5898e',
    messagingSenderId: '948860137355',
    projectId: 'wachat-nk',
    authDomain: 'wachat-nk.firebaseapp.com',
    storageBucket: 'wachat-nk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHmpVW4lcuEyqG4cQl118UX3nQISD_StE',
    appId: '1:948860137355:android:e7ce2e2a25cdf6cad5898e',
    messagingSenderId: '948860137355',
    projectId: 'wachat-nk',
    storageBucket: 'wachat-nk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu6xZG1iDlkN1RwYV_pssX3SSplBtsCdQ',
    appId: '1:948860137355:ios:6148714b6b1ca502d5898e',
    messagingSenderId: '948860137355',
    projectId: 'wachat-nk',
    storageBucket: 'wachat-nk.appspot.com',
    iosBundleId: 'com.example.wachat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu6xZG1iDlkN1RwYV_pssX3SSplBtsCdQ',
    appId: '1:948860137355:ios:f28cd07295ef809ad5898e',
    messagingSenderId: '948860137355',
    projectId: 'wachat-nk',
    storageBucket: 'wachat-nk.appspot.com',
    iosBundleId: 'com.example.wachat.RunnerTests',
  );
}
